import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import "./globals.css"

const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Code Sharing App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased bg-gradient-to-br from-[#b787f5] to-[#743ee4]`}
      >
        {children}
      </body>
    </html>
  )
}
